services:
  titiler:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
    environment:
      - TITILER_API_ROOT_PATH=/tiler
      - TITILER_API_CACHECONTROL=no-cache
      - REDIS_HOST=redis
    command: ["uv", "run", "uvicorn", "src.app.app:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    depends_on:
      - redis

  redis:
    image: redis
  