services:
  titiler:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "5002:8080"
    volumes:
      - ./src:/app/src
    environment:
      - TITILER_API_ROOT_PATH=/tiler
      - TITILER_API_CACHECONTROL=no-cache
      - REDIS_HOST=redis
    command: ["pdm", "run", "uvicorn", "src.app.app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

  redis:
    image: redis
  